### ISSUE TITLE
Support embedded structs

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cq-gen#136]
Some Go SDKs, e.g. [this one](https://github.com/heroku/heroku-go/blob/3f3061431e5ab137e9c4d4860382b50e7b887888/v5/heroku.go#L4200-L4224) make use of embedded structs. Right now, cq-gen panics when reading such a struct:

```
panic: type

goroutine 1 [running]:
github.com/cloudquery/cq-gen/codegen/source/golang.getNamedType({0x1055543c8?, 0x1400115e480?})
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/source/golang/types.go:87 +0xe0
github.com/cloudquery/cq-gen/codegen/source/golang.getNamedType({0x105554350?, 0x14001156420?})
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/source/golang/types.go:81 +0x90
github.com/cloudquery/cq-gen/codegen/source/golang.FieldObject.Fields({{0x14000163710, 0x23}, {0x14000207f40, {0x105551478, 0x105950df8}}, 0x1400114fd10, {0x105557fd0, 0x14001d1f740}, {0x0, 0x0}})
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/source/golang/source.go:118 +0x90
github.com/cloudquery/cq-gen/codegen.TableBuilder.buildColumns({{{0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, 0x0}}, {0x1055514b8, 0x14000121d70}, 0x14000121d58, ...}, ...)
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/builder.go:242 +0x70
github.com/cloudquery/cq-gen/codegen.TableBuilder.buildColumn({{{0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, 0x0}}, {0x1055514b8, 0x14000121d70}, 0x14000121d58, ...}, ...)
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/builder.go:332 +0x1084
github.com/cloudquery/cq-gen/codegen.TableBuilder.buildColumns({{{0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, 0x0}}, {0x1055514b8, 0x14000121d70}, 0x14000121d58, ...}, ...)
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/builder.go:250 +0x4c8
github.com/cloudquery/cq-gen/codegen.TableBuilder.BuildTable({{{0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, 0x0}}, {0x1055514b8, 0x14000121d70}, 0x14000121d58, ...}, ...)
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/builder.go:158 +0x7cc
github.com/cloudquery/cq-gen/codegen.buildResources(0x1400013f180, {0x0, 0x0}, {0x0, 0x0})
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/data.go:86 +0x664
github.com/cloudquery/cq-gen/codegen.Generate({0x16b04336c, 0x7}, {0x0, 0x0}, {0x0, 0x0}, {0x16b04337d, 0x1})
	/Users/hermanschaaf/code/cloudquery/cq-gen/codegen/generate.go:32 +0x104
main.main()
	/Users/hermanschaaf/code/cloudquery/cq-gen/main.go:17 +0x1a0
```

**Comment by yevgenypats** [comment]
I think in general embedded structs or fields should always be json as it's not CQ responsibility to do more transformation than the very first one. So if we just skip those I think it might work.
